navbar:
  - events: /collections/events.html
  - manifesto: /collections/manifesto.html
  - design: /collections/design.html
  - gallery: /gallery.html
  - members: /collections/members.html
  - about: /about.html
baseURL: https://anirudhsudhir.github.io/test-hsp/
siteTitle: "HSP"
siteScripts: ["hamburger.js"]
author: HSP
themeURL: "/static/default_imports.css"
copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International."
collectionLayouts:
  - collections/members.html: collection-subpage-mem
